name: Pull Request on Github
on: [pull_request]
jobs:
  PullRequest-GitHub:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Make a new envfile
        uses: SpicyPizza/create-envfile@v1.3
        with:
          envkey_POSTGRES_USER: ${{secrets.POSTGRES_USER}}
          envkey_POSTGRES_PASSWORD: ${{secrets.POSTGRES_PASSWORD}}
          envkey_POSTGRES_DB: "students-test"
          envkey_DATABASE_URL: "postgres://postgres:postgres@sorteador_db_test:5432/students-test"
          directory: back-end
          file_name: .env.test
      - name: Run tests
        run: docker-compose -f docker-compose-test.yml run sorteador_api_test npm run test